apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vctrlpod4
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "host-device",
      "device": "vctrlpod4"
    }'
